config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "home#index"

  resources :contributions, only: [:create, :index, :destroy, :update] do
  end

  resources :operations, only: [:create, :index, :destroy, :update] do
    post 'copy', to: 'operations#copy', as: 'copy'
  end

  get 'income_tax', to: 'income_tax#get_income_tax', as: 'get_income_tax'
  get 'kpir', to: 'kpir#get_kpir', as: 'get_kpir'
  get 'kpir_by_month', to: 'kpir#get_kpir_by_month', as: 'get_kpir_by_month'
  get 'year_summary', to: 'kpir#year_summary', as: 'year_summary'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/views/home/_header.html.slim
nav.navbar.navbar-default.navbar-static-top role="navigation" 
  .container-fluid
    a.navbar-brand 
      span.glyphicon.glyphicon-time
      = I18n.t('application_name')
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        - if user_signed_in?
          li= active_link_to I18n.t('contributions.index'), contributions_path
          li= active_link_to I18n.t('operations.index'), operations_path
          li= active_link_to I18n.t('income_tax.header'), get_income_tax_path
          li= active_link_to I18n.t('kpir.header'), get_kpir_path(date: Date.today.strftime("%Y"))
          li= active_link_to I18n.t('kpir.header_by_month'), get_kpir_by_month_path(date: Date.today.strftime("%Y"))
          li= active_link_to I18n.t('kpir.year_summary'), year_summary_path(date: Date.today.strftime("%Y"))
          - unless current_user.email == 'demo@example.com'
            li= active_link_to I18n.t('user.edit'), edit_user_registration_path
          li= active_link_to I18n.t('user.logout'), destroy_user_session_path, method: :delete
        - else
          li= active_link_to I18n.t('user.registration'), new_user_registration_path
          li= active_link_to I18n.t('user.login'), user_session_path
      /ul.nav.navbar-nav.pull-right
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
            span.glyphicon.glyphicon-globe
            span.caret
          ul.dropdown-menu.dropdown-menu-right
            li 
              = link_to params.permit(:locale, :user_id).merge({:locale => :pl}), :wrap_tag => :li
                span = image_tag("pl.jpg", :alt => "pl", style: "border: 1px solid black" )
                span = " Polski"
            li 
              = link_to params.permit(:locale, :user_id).merge({:locale => :en}), :wrap_tag => :li
                span = image_tag("en.jpg", :alt => "en", style: "border: 1px solid black")
                span = " English"
        

app/views/home/index.html.slim
h1
    | Hello world