config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "home#index"

  resources :contributions, only: [:create, :index, :destroy, :update] do
  end

  resources :operations, only: [:create, :index, :destroy, :update] do
    post 'copy', to: 'operations#copy', as: 'copy'
  end

  get 'income_tax', to: 'income_tax#get_income_tax', as: 'get_income_tax'
  get 'kpir', to: 'kpir#get_kpir', as: 'get_kpir'
  get 'kpir_by_month', to: 'kpir#get_kpir_by_month', as: 'get_kpir_by_month'
  get 'year_summary', to: 'kpir#year_summary', as: 'year_summary'
end

app/models/contribution.rb
class Contribution < ApplicationRecord
    belongs_to :user
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
    before_action :authenticate_user!

    def index
      @contributions = current_user.contributions.order(date: :desc).paginate(:page => params[:page], :per_page => 10)
    end
  
    def create
      begin
        c = Contribution.new(contribution_params)
        c.user = current_user
        c.save!

      rescue => e
        flash[:danger] = I18n.t('contributions.save_failure')
      end
  
      redirect_to contributions_path
    end
  
    def update 
      begin
        @contribution = Contribution.find(params[:id])
        @contribution.update!(contribution_params)
      rescue => e
        flash[:danger] = I18n.t('contributions.save_failure')
      end
      redirect_to contributions_path  
    end
  
    def destroy
      Contribution.destroy(params[:id])
      redirect_to contributions_path
    end
  
    private
  
    def contribution_params
      params.require(:contribution).permit(:contribution_type, :date, :amount)  
    end  
  end
  

app/views/contributions/_add_contribution.html.slim
= form_for :contribution, url: contributions_path, turboboost: true, method: :post  do |f|
  .modal.fade#add_contribution tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header 
          = I18n.t('contributions.add_contribution')
        .modal-body
          .row
            .col-md-6
              .form-group
                = f.label :date, I18n.t('contributions.date')
                = f.text_field :date, autocomplete: "off", class: 'form-control datepicker', data: {provide: 'datepicker'}, value: Date.today
            .col-md-6
              .form-group
                = f.label :contribution_type, I18n.t('contributions.type')
                = f.select :contribution_type, ['tax', 'civil', 'health'].map{|t| [I18n.t("contributions.#{t}"), t]}, {}, {class: 'form-control'}
          .row
            .col-md-6
              .form-group
                = f.label :amount, I18n.t('contributions.amount')
                = f.text_field :amount, class: 'form-control'
                 
        .modal-footer
          button.btn.custom-btn type="submit" 
            = I18n.t('save')
          button.btn.btn-default data-dismiss="modal" 
            = I18n.t('cancel')

app/views/contributions/_edit_form.html.slim
= form_for contribution, url: contribution_path(contribution), turboboost: true, method: :patch  do |f|
  .modal.fade id="contribution_edit_#{contribution.id}" tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header 
          = I18n.t('contributions.edit_contribution')
        .modal-body
          .row
            .col-md-6
              .form-group
                = f.label :date, I18n.t('contributions.date')
                = f.text_field :date, autocomplete: "off", class: 'form-control datepicker', data: {provide: 'datepicker'}
            .col-md-6
              .form-group
                = f.label :contribution_type, I18n.t('contributions.type')
                = f.select :contribution_type, ['tax', 'civil', 'health'].map{|t| [I18n.t("contributions.#{t}"), t]}, {}, {class: 'form-control'}
          .row
            .col-md-6
              .form-group
                = f.label :amount, I18n.t('contributions.amount')
                = f.text_field :amount, class: 'form-control'
                 
        .modal-footer
          button.btn.custom-btn type="submit" 
            = I18n.t('save')
          button.btn.btn-default data-dismiss="modal" 
            = I18n.t('cancel')

app/views/contributions/_edit_forms.html.slim
- @contributions.each do |contribution|
  = render partial: 'edit_form', locals: {contribution: contribution}

app/views/contributions/index.html.slim
.panel.panel-default
  .panel-heading
    = I18n.t('contributions.index')
    .btn-group.pull-right
      button.btn.btn-xs.custom-btn-lighter data-toggle="modal" data-target="#add_contribution" type="button"
        span.glyphicon.glyphicon-plus
  .panel-body
    table.table.table-hover
      thead
        tr
          th width="30%" = I18n.t('contributions.date') 
          th width="30%" = I18n.t('contributions.type')
          th width="30%" = I18n.t('contributions.amount')
          th width="10%"
      tbody 
      - @contributions.each do |contribution|
        tr 
          td 
            = contribution.date
          td 
            = t("contributions.#{contribution.contribution_type}")
          td 
            = contribution.amount
          td 
            .btn-group.pull-right
              button.btn.btn-xs.custom-btn data-toggle="modal" data-target="#contribution_edit_#{contribution.id}"
                span.glyphicon.glyphicon-pencil
              =link_to contribution_path(contribution), class: 'btn btn-xs custom-btn', method: :delete, data: {confirm: I18n.t('contributions.delete_confirmation_message')}
                span.glyphicon.glyphicon-remove
        
= render "add_contribution"
= render "edit_forms"
.center
  = will_paginate @operations, renderer: BootstrapPagination::Rails