config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "home#index"

  resources :contributions, only: [:create, :index, :destroy, :update] do
  end

  resources :operations, only: [:create, :index, :destroy, :update] do
    post 'copy', to: 'operations#copy', as: 'copy'
  end

  get 'income_tax', to: 'income_tax#get_income_tax', as: 'get_income_tax'
  get 'kpir', to: 'kpir#get_kpir', as: 'get_kpir'
  get 'kpir_by_month', to: 'kpir#get_kpir_by_month', as: 'get_kpir_by_month'
  get 'year_summary', to: 'kpir#year_summary', as: 'year_summary'
end

app/models/operation.rb
class Operation < ActiveRecord::Base
  belongs_to :user

  validates :date, presence: true
  validates :amount, presence: true

end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @operations = nil
    @operations = current_user.operations.order(date: :desc).paginate(:page => params[:page], :per_page => 10)
  end
    
  def create
    begin
      o = Operation.new(operation_params)
      o.user = current_user
      o.save!
    rescue => e
      flash[:danger] = I18n.t('operations.save_failure')
    end

    redirect_to operations_path
  end

  def destroy
    Operation.destroy(params[:id])
    redirect_to operations_path
  end

  def update
    begin 
      @operation = Operation.find(params[:id])
      @operation.update!(operation_params)
    rescue => e
      flash[:danger] = I18n.t('operations.save_failure')
    end
    redirect_to operations_path    
    
  end

  def copy
    begin 
      operation = Operation.find(params[:operation_id])

      operation2 = Operation.new(operation.attributes)
      operation2.id = nil
      operation2.date = Time.now.to_date

      operation2.save!
    rescue => e
      flash[:danger] = I18n.t('operations.save_failure')
    end
    redirect_to operations_path 
  end

  private
  def operation_params
    permit_params = params.require(:operation).permit(:date, :operation_type, :description, :amount, :invoice_no, :contractor_name, :contractor_address, :operation_subtype, :other_cost_amount)
    permit_params['amount'] = permit_params['amount'].gsub(',', '.').to_f.round(2).to_s
    permit_params
  end

end

app/views/operations/_add_operation.html.slim
= form_for :operation, url: operations_path, turboboost: true, method: :post  do |f|
  .modal.fade id="add_operation_#{type}" tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header 
          = I18n.t('operations.add_operation')
        .modal-body
          .row
            .col-md-6
              .form-group
                = f.label :date, I18n.t('operations.date')
                = f.text_field :date, autocomplete: "off", class: 'form-control datepicker', data: {provide: 'datepicker'}, value: Date.today
            .col-md-6
              .form-group
                = f.label :operation_type, I18n.t('operations.type')
                = f.select :operation_type, [type.camelize].map{|o| [I18n.t("operations.#{o.downcase}"), o]}, {}, {class: 'form-control', readonly: 'true', value: type.camelize}
          .row
            .col-md-6
              .form-group
                = f.label :amount, I18n.t('operations.amount')
                = f.text_field :amount, autocomplete: "off", class: 'form-control'
            - if type == 'cost'
              .col-md-6
                .form-group
                  = f.label :other_cost_amount, I18n.t('operations.other_cost_amount')
                  = f.text_field :other_cost_amount, class: 'form-control'
          .row
            .col-md-6
              .form-group
                = f.label :invoice_no, I18n.t('operations.invoice_no')
                = f.text_field :invoice_no, class: 'form-control'
            .col-md-6
              .form-group
                = f.label :operation_subtype, I18n.t('operations.operation_subtype')
                - if type == 'revenue'
                  - subtypes = ['col_7', 'col_8']
                - else
                  - subtypes = ['col_10', 'col_12', 'col_13', 'col_16']
                = f.select :operation_subtype, subtypes.map{|o| [I18n.t("operations.#{o}"), o]}, {}, {class: 'form-control'}
          .row
            .col-md-6
              .form-group
                = f.label :contractor_name, I18n.t('operations.contractor_name')
                = f.text_area :contractor_name, class: 'form-control'
            .col-md-6
              .form-group
                = f.label :contractor_address, I18n.t('operations.contractor_address')
                = f.text_area :contractor_address, class: 'form-control'
          .row
            .col-md-12
              .form-group
                = f.label :description, I18n.t('operations.description')
                = f.text_area :description, class: 'form-control'
          
        .modal-footer
          button.btn.custom-btn type="submit" 
            = I18n.t('save')
          button.btn.btn-default data-dismiss="modal" 
            = I18n.t('cancel')

app/views/operations/_edit_form.html.slim
= form_for operation, url: operation_path(operation),  turboboost: true, method: :patch  do |f|
  .modal.fade id="operation_edit_#{operation.id}" tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header 
          = I18n.t('operations.edit_operation')
        .modal-body
          .row
            .col-md-6
              .form-group
                = f.label :date, I18n.t('operations.date')
                = f.text_field :date, autocomplete: "off", class: 'form-control datepicker', data: {provide: 'datepicker'}
            .col-md-6
              .form-group
                = f.label :operation_type, I18n.t('operations.type')
                = f.select :operation_type, [operation.operation_type.camelize].map{|o| [I18n.t("operations.#{o.downcase}"), o]}, {}, {class: 'form-control', disabled: 'true', value: operation.operation_type.camelize}
          .row
            .col-md-6
              .form-group
                = f.label :amount, I18n.t('operations.amount')
                = f.text_field :amount, autocomplete: "off", class: 'form-control'
            - if operation.operation_type.downcase == 'cost'
              .col-md-6
                .form-group
                  = f.label :other_cost_amount, I18n.t('operations.other_cost_amount')
                  = f.text_field :other_cost_amount, class: 'form-control'
          .row
            .col-md-6
              .form-group
                = f.label :invoice_no, I18n.t('operations.invoice_no')
                = f.text_field :invoice_no, class: 'form-control'
            .col-md-6
              .form-group
                = f.label :operation_subtype, I18n.t('operations.operation_subtype')
                - if operation.operation_type.downcase == 'revenue'
                  - subtypes = ['col_7', 'col_8']
                - else
                  - subtypes = ['col_10', 'col_12', 'col_13', 'col_16']
                = f.select :operation_subtype, subtypes.map{|o| [I18n.t("operations.#{o}"), o]}, {}, {class: 'form-control'}
          .row
            .col-md-6
              .form-group
                = f.label :contractor_name, I18n.t('operations.contractor_name')
                = f.text_area :contractor_name, class: 'form-control'
            .col-md-6
              .form-group
                = f.label :contractor_address, I18n.t('operations.contractor_address')
                = f.text_area :contractor_address, class: 'form-control'
          .row
            .col-md-12
              .form-group
                = f.label :description, I18n.t('operations.description')
                = f.text_area :description, class: 'form-control'
          
        .modal-footer
          button.btn.custom-btn type="submit" 
            = I18n.t('save')
          button.btn.btn-default data-dismiss="modal" 
            = I18n.t('cancel')

app/views/operations/_edit_forms.html.slim
- @operations.each do |operation|
  = render partial: 'edit_form', locals: {operation: operation}

app/views/operations/index.html.slim
.panel.panel-default.operation-panel
  .panel-heading
    = I18n.t('operations.index')
    .btn-group.pull-right
      button class="btn btn-xs custom-btn-lighter dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
        span.glyphicon.glyphicon-plus
        span.caret
      ul.dropdown-menu.dropdown-menu-right
        li 
          = link_to t("operations.add_cost"), "#add_operation_cost", "data-toggle" => "modal"
        li 
          = link_to t("operations.add_revenue"), "#add_operation_revenue", "data-toggle" => "modal"
        
  .panel-body                
    table.table.table-hover 
      thead
        tr
          th width="8%" = I18n.t('operations.date')
          th width="6%" = I18n.t('operations.type')
          th width="8%" = I18n.t('operations.amount')
          th width="46%" = I18n.t('operations.description') 
          th width="10%"
      tbody 
        - @operations.each do |operation|
          tr 
            td
              = operation.date
            td 
              = I18n.t("operations.#{operation.operation_type.downcase}") 
            td 
              = operation.amount
            td 
              = operation.description
            td 
              .btn-group.pull-right
                =link_to operation_copy_path(operation), class: 'btn btn-xs custom-btn', method: :post
                  span.glyphicon.glyphicon-duplicate
                button.btn.btn-xs.custom-btn data-toggle="modal" data-target="#operation_edit_#{operation.id}"
                  span.glyphicon.glyphicon-pencil
                =link_to operation_path(operation), class: 'btn btn-xs custom-btn', method: :delete, data: {confirm: I18n.t('operations.delete_confirmation_message')}
                  span.glyphicon.glyphicon-remove

= render "add_operation", :type => 'cost'
= render "add_operation", :type => 'revenue'
= render "edit_forms"
.center
  = will_paginate @operations, renderer: BootstrapPagination::Rails